// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface Link {
  title: string;
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "link";
  _uid: string;
}

export interface Page {
  blocks?: (Link | Page | Post | Project | Settings)[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "page";
  _uid: string;
}

export interface Post {
  category: (number | string)[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "post";
  _uid: string;
}

export interface Project {
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "project";
  _uid: string;
}

export interface Settings {
  component: "settings";
  _uid: string;
}

export type ContentType = Page | Post | Project | Settings;
